### PR TITLE
Convert tween kind to an abstract class

### LINKED ISSUE #17: Tween kind as an abstract class?
@ddfreyne What do you think of changing `Glove::Tween::Kind` so, rather than an enum, it is a module containing classes that each implement a single abstract class with a `calc(lf)` method? This would allow for easy creation of custom tweening algorithms.

I just wanted to get your thoughts on it before I make a PR for it as it *would* be a significant breaking change.

### PR DESCRIPTION
**Pull request by Qard**
This allows custom tweening algorithms to be made with ease.

Fixes #17

### CODE REVIEW

**Review by denisdefreyne — APPROVED** [review]

**Comment by denisdefreyne** [comment]
You could _probably_ retain backwards compatibility (always nice) by creating a second constructor that takes a class:

```crystal
def initialize(duration : Float32, kind_class : Class)
  initialize(duration, kind_class.new)
end
```

**Comment by Qard** [comment]
I tried the second constructor idea, but with `Kind.class` rather than `Class`, which works but would require anything that accepts a tween kind as an argument to change from `Glove::Tween::Kind` to `Glove::Tween::Kind.class` to work properly. Using `Class` would require a change too...there's not really a way to avoid having to change the argument types that currently reference `Glove::Tween::Kind`.

**Comment by denisdefreyne** [comment]
Oh well!

Feel free to merge this PR whenever.

**Comment by denisdefreyne** [comment]
@Qard Is there anything preventing this PR from being merged? If not, merge!

**Comment by Qard** [comment]
I've busy with traveling and work recently, so I haven't had time to get back to this. I'll probably merge it some time this weekend.

**Comment by Qard** [comment]
Sorry for the huge delay with merging this. I wanted some time for a final review to make sure there was nothing more I could do to maintain compatibility. I've been traveling a bunch for work over the last couple weeks, so I wasn't able to give it the review it needed until today.

Anyway, I think I'll just merge it as it is now. It'll break any external code that currently expects a `Glove::Tween::Kind` as an input argument, but that's a trivial fix of just adding `.class` after it. 🤷‍♂️

**Pull request merged**
