### PR TITLE
Use external stb_image and glew to simplify the project

### PR DESCRIPTION
**Pull request by Qard**
Just externalizing some things that don't need to be in the project itself.

### CODE REVIEW

**Comment by denisdefreyne** [comment]
I think the Makefile will have to be updated, too:

```
$ make spec
*** Building ext…
make -C src/ext
make: *** src/ext: No such file or directory.  Stop.
make: *** [ext] Error 2
```

**Comment by denisdefreyne** [comment]
`+9 −6555` :heart_eyes:

**Comment by Qard** [comment]
Fixed. This should be done now, I think. Might look at pulling other things out too, but they are bigger and more complicated dependencies. 🤔

**Review by denisdefreyne — APPROVED** [review]

**Comment by denisdefreyne** [comment]
Looks good! Feel free to merge.

**Pull request merged**
